name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          npx playwright install
          npx playwright test
        continue-on-error: true

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Add Playwright report to summary
        if: always()
        run: |
          echo '### Playwright Test Report' >> $GITHUB_STEP_SUMMARY
          echo '<details><summary>Click to view report</summary>' >> $GITHUB_STEP_SUMMARY
          echo '<p>' >> $GITHUB_STEP_SUMMARY
          REPORT_URL=$(realpath playwright-report/index.html)
          echo "<a href=\"file://$REPORT_URL\">Playwright Test Report</a>" >> $GITHUB_STEP_SUMMARY
          echo '</p></details>' >> $GITHUB_STEP_SUMMARY
