name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          npx playwright install
          npx playwright test
        continue-on-error: true

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Parse Playwright JSON report
        id: parse_report
        run: |
          REPORT_PATH="playwright-report/report.json"
          TOTAL=$(jq '.suites | length' $REPORT_PATH)
          PASSED=$(jq '[.suites[] | select(.status == "passed")] | length' $REPORT_PATH)
          FAILED=$(jq '[.suites[] | select(.status == "failed")] | length' $REPORT_PATH)
          SKIPPED=$(jq '[.suites[] | select(.status == "skipped")] | length' $REPORT_PATH)
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "passed=$PASSED" >> $GITHUB_ENV
          echo "failed=$FAILED" >> $GITHUB_ENV
          echo "skipped=$SKIPPED" >> $GITHUB_ENV

      - name: Add Playwright report to summary
        if: always()
        run: |
          echo '### Playwright Test Report' >> $GITHUB_STEP_SUMMARY
          echo 'Click to view report: [Playwright Test Report](./playwright-report/index.html)' >> $GITHUB_STEP_SUMMARY
          echo '#### Test Summary' >> $GITHUB_STEP_SUMMARY
          echo "- Total tests: ${{ env.total }}" >> $GITHUB_STEP_SUMMARY
          echo "- Passed tests: ${{ env.passed }}" >> $GITHUB_STEP_SUMMARY
          echo "- Failed tests: ${{ env.failed }}" >> $GITHUB_STEP_SUMMARY
          echo "- Skipped tests: ${{ env.skipped }}" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
